apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bitwarden-eso.fullname" . }}-credentials
  labels:
    {{- include "bitwarden-eso.labels" . | nindent 4 }}
type: Opaque
stringData:
  BW_HOST: {{ .Values.bitwarden.host | quote }}
  BW_USER: {{ .Values.bitwarden.username | quote }}
  BW_PASSWORD: {{ .Values.bitwarden.password | quote }}
  {{- if .Values.bitwarden.clientId }}
  BW_CLIENTID: {{ .Values.bitwarden.clientId | quote }}
  {{- end }}
  {{- if .Values.bitwarden.clientSecret }}
  BW_CLIENTSECRET: {{ .Values.bitwarden.clientSecret | quote }}
  {{- end }}