apiVersion: v1
kind: Service
metadata:
  name: {{ include "bitwarden-eso.fullname" . }}
  labels:
    {{- include "bitwarden-eso.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8087
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "bitwarden-eso.selectorLabels" . | nindent 4 }}