apiVersion: v2
name: bitwarden-password-manager-eso
description: Bitwarden CLI + ClusterSecretStore for External Secrets Operator
type: application
version: 1.2.5
appVersion: 2026.1.0
icon: >-
  https://user-cube.github.io/bitwarden-password-manager-eso/docs/assets/logo-64x64.png

annotations:
  artifacthub.io/category: security
  artifacthub.io/changes: |
    - kind: changed
      description: Release 1.2.5
