apiVersion: v2
name: bitwarden-password-manager-eso
description: Bitwarden CLI + ClusterSecretStore for External Secrets Operator
type: application
version: 1.2.4
appVersion: 2026.1.0
icon: https://user-cube.github.io/bitwarden-password-manager-eso/docs/assets/logo-64x64.png
