name: Release & Publish Helm

on:
  push:
    branches:
      - main
      - master

permissions:
  contents: write
  packages: write

concurrency:
  group: gh-pages
  cancel-in-progress: false

jobs:
  release:
    name: Semantic Release
    uses: user-cube/reusable-cicd/.github/workflows/semantic-release_simple-release.yml@main
    with:
      node-version: "20"
      extra-plugins: |
        semantic-release-helm
        @semantic-release/exec
      pre-install: |
        version=v1.14.2
        curl -sSLo /tmp/helm-docs.tar.gz "https://github.com/norwoodj/helm-docs/releases/download/${version}/helm-docs_${version#v}_Linux_x86_64.tar.gz"
        tar -xzf /tmp/helm-docs.tar.gz -C /tmp helm-docs
        install -m 755 /tmp/helm-docs /usr/local/bin/helm-docs
    secrets:
      GITHUB_APP_ID: ${{ secrets.DEVOPS_BUDDY_APP_ID }}
      GITHUB_APP_PRIVATE_KEY: ${{ secrets.DEVOPS_BUDDY_PRIVATE_KEY }}

  publish:
    name: Publish Helm Chart
    needs: release
    if: needs.release.outputs.new-release == 'true'
    uses: user-cube/reusable-cicd/.github/workflows/helm-releaser.yml@main
    with:
      charts_dir: charts
      config: .github/configs/cr.yaml
      push_oci: true
    secrets:
      GITHUB_APP_ID: ${{ secrets.DEVOPS_BUDDY_APP_ID }}
      GITHUB_APP_PRIVATE_KEY: ${{ secrets.DEVOPS_BUDDY_PRIVATE_KEY }}

  docs:
    name: Build and Publish Docs
    needs: [release, publish]
    if: needs.release.outputs.new-release == 'true'
    uses: user-cube/reusable-cicd/.github/workflows/mkdocs-helm_deploy.yml@main
    with:
      python-version: "3.x"
      docs-subdir: "docs"
      pages-branch: "gh-pages"
    secrets:
      GITHUB_APP_ID: ${{ secrets.DEVOPS_BUDDY_APP_ID }}
      GITHUB_APP_PRIVATE_KEY: ${{ secrets.DEVOPS_BUDDY_PRIVATE_KEY }}